language: node_js

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm ci

jobs:
  include:
    - node_js: "8"
    - node_js: "10"
    - node_js: "12"
      env: FORMDATA_VERSION=1.0.0
    - node_js: "12"
      env: FORMDATA_VERSION=2.5.1
    - node_js: "12"
      env: ELECTRON_VERSION=4.2.12
    - node_js: "12"
      env: ELECTRON_VERSION=5.0.12
    - node_js: "12"
      env: ELECTRON_VERSION=6.1.4 # This is the default
#    - node_js: "12"
#      env: ELECTRON_VERSION=7.1.1 # Disabled for now, because it is broken

before_script:
  - 'if [ "$FORMDATA_VERSION" ]; then npm install form-data@^$FORMDATA_VERSION; fi'
  - 'if [ "$ELECTRON_VERSION" ]; then npm install electron@^$ELECTRON_VERSION; fi'

script: npm run report

cache:
  directories:
    - node_modules
